steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/skin-prediction', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/skin-prediction']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'skin-prediction',
        '--image',
        'gcr.io/$PROJECT_ID/skin-tumor-flask-app',
        '--platform',
        'managed',
        '--region',
        'us-central1',       # Change selon ta région GCP
        '--allow-unauthenticated',
        '--port',
        '5000'
      ]
